### ISSUE TITLE
不支持两个字符的搜索模式吗？

### ISSUE THREAD

**Issue by BSDxxxx** [ZSaberLv0/vim-easymotion-chs#1]

**Comment by ZSaberLv0** [comment]
简单结论: 没有简单的方式能实现, 真想折腾的话可以参见下文详细

复杂结论:

你可以参考下 `EasyMotion#cmigemo#getMigemoPattern` 相关的源码, 这货依赖于 `migemo` 生成的码表, 并用这个码表来根据输入生成对应的正则, 但是很遗憾, 这玩意儿全是为日文服务的

想搞的话, 也有很复杂的方式可能可以实现 (我没尝试, 因为我不用 `<Plug>(easymotion-s2)` , 也不打算去折腾这种麻烦事):
* 替换掉 `EasyMotion#cmigemo#getMigemoPattern`, 获取当前屏幕里的中文字符, 并根据输入匹配并返回中文字符的正则
