### ISSUE TITLE
`vim-easymotion-chs` 干扰了正常 `<Plug>(easymotion-s2)` 搜索操作

### ISSUE THREAD

**Issue by pilgrimlyieu** [ZSaberLv0/vim-easymotion-chs#2]
已经看过了 #1，清楚不支持两个字符的搜索模式。

但是如果想要正常搜索两个字母时会跳出一次警告，随后就不再跳出。能否进行修复？非常感谢！

![Snipaste_2022-07-26_17-47-10](https://user-images.githubusercontent.com/80107081/180977227-f0e1e0ae-3cf9-4320-9cac-061c0d6ea8fc.png)

**Comment by ZSaberLv0** [comment]
"正常搜索两个字母" 是什么意思？列一下具体的操作方式吧？

**Comment by pilgrimlyieu** [comment]
> "正常搜索两个字母" 是什么意思？列一下具体的操作方式吧？

例如我映射了 <kbd>,</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd>

```vimrc
nnoremap <leader>S         <Plug>(easymotion-s2)
```

```txt
这是目标缓冲区

abcdef
```

我想要搜索 `cd`，于是我按了<kbd>,</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd>，输入 `cd` 后立刻显示上面的警告，然后消失。

**Comment by pilgrimlyieu** [comment]
可以正常工作了，非常感谢！
